GOLD MINE DESIGN

In [2]:
def Gold_Design(f,n,m):
    for col in range(m):
        for row in range(n):
            if(col==0):
                right=0
            else:
                right=f[row][col-1]
            if(col==0 or row==0):
                right_up=0
            else:
                 right_up=f[row-1][col-1]  #right_down
            if(col==0 or row==n-1):
                right_down=0
            else:
                right_down=f[row+1][col-1] #right_up
            maximum=max(right,right_up,right_down)
            f[row][col]=f[row][col]+maximum
    res=f[0][m-1]
    for i in range(n):
        res=max(res,f[i][m-1])
    print("\n**********************************************************************")
    print("The maximum gold the miner can collect is {} tons of gold....".format(res))
    print("**********************************************************************")
    print("END-"*30)
    print(f)

In [3]:
import numpy as np
n=int(input("Enter no of rows"))
m=int(input("Enter no of columns"))
field=np.zeros([n,m],dtype=int)

Enter no of rows3
Enter no of columns3


In [4]:
for i in range(n):
    for j in range(m):
        field[i][j]=int(input("Enter how many tons of gold in {}-{} field".format(i,j)))
print("The field is given below......")
print(field)
Gold_Design(field,n,m)

Enter how many tons of gold in 0-0 field1
Enter how many tons of gold in 0-1 field2
Enter how many tons of gold in 0-2 field3
Enter how many tons of gold in 1-0 field1
Enter how many tons of gold in 1-1 field2
Enter how many tons of gold in 1-2 field1
Enter how many tons of gold in 2-0 field1
Enter how many tons of gold in 2-1 field2
Enter how many tons of gold in 2-2 field1
The field is given below......
[[1 2 3]
 [1 2 1]
 [1 2 1]]

**********************************************************************
The maximum gold the miner can collect is 6 tons of gold....
**********************************************************************
END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-END-
[[1 3 6]
 [1 3 4]
 [1 3 4]]
